/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Adriana Julian
 */
public class ColaArbol extends javax.swing.JFrame {
    @Override
public void paint(java.awt.Graphics g) {
    super.paint(g); // Mantiene los componentes básicos si los hay
    
    // Antialiasing para que los círculos se vean suaves y no "pixelados"
    java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
    g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

    // Dibujamos el árbol empezando desde la raíz (índice 0)
    // Parámetros: Graphics, índice, x inicial, y inicial, espacio entre nodos
    dibujarArbol(g2, 0, getWidth() / 2, 80, getWidth() / 4);
}

private void dibujarArbol(java.awt.Graphics2D g, int i, int x, int y, int xOffset) {
    EDD.MonticuloMinimo monticulo = Interfaces.Inicio.colaImpresion;
    
    if (i < monticulo.getSize()) {
        EDD.ElementoMonticulo[] arreglo = monticulo.getHeap();
        MainClass.RegistroImpresion reg = (MainClass.RegistroImpresion) arreglo[i].getData();
        String etiqueta = String.valueOf(reg.getEtiquetaTiempo());

        // 1. Dibujar conexiones con los hijos primero (para que queden detrás de los círculos)
        g.setColor(java.awt.Color.BLACK);
        int hijoIzq = 2 * i + 1;
        int hijoDer = 2 * i + 2;

        if (hijoIzq < monticulo.getSize()) {
            g.drawLine(x, y, x - xOffset, y + 60);
            dibujarArbol(g, hijoIzq, x - xOffset, y + 60, xOffset / 2);
        }
        if (hijoDer < monticulo.getSize()) {
            g.drawLine(x, y, x + xOffset, y + 60);
            dibujarArbol(g, hijoDer, x + xOffset, y + 60, xOffset / 2);
        }

        // 2. Dibujar el Nodo (Círculo)
        g.setColor(new java.awt.Color(100, 149, 237)); // Color azul bonito (Cornflower Blue)
        g.fillOval(x - 20, y - 20, 40, 40);
        g.setColor(java.awt.Color.DARK_GRAY);
        g.drawOval(x - 20, y - 20, 40, 40);

        // 3. Dibujar la Etiqueta (Texto)
        g.setColor(java.awt.Color.WHITE);
        g.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
        // Ajuste para centrar el texto según si es 1, 2 o 3 dígitos
        int adjustX = (etiqueta.length() > 1) ? -10 : -5;
        g.drawString(etiqueta, x + adjustX, y + 5);
    }
}

    /**
     * Creates new form ColaArbol
     */
    public ColaArbol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Grafica de Cola(Arbol)");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Interfaces.Inicio menu = new Interfaces.Inicio();
menu.setVisible(true);


this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColaArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColaArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColaArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColaArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColaArbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
