/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import javax.swing.JFrame;
/**
 *
 * @author Adriana
 */
public class Inicio extends javax.swing.JFrame {
    public static EDD.TablaHash tablaUsuarios = new EDD.TablaHash(100); 
    public static EDD.MonticuloMinimo colaImpresion = new EDD.MonticuloMinimo(100);
    public static MainClass.RelojSistema reloj = new MainClass.RelojSistema();
    public static EDD.TablaHash duenosDocumentos = new EDD.TablaHash(100);
    public static int tiempoSistema = 0;

    


    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null); // Centrar ventana
        this.setTitle("Sistema de Gestión de Impresión");
        this.setSize(500, 400); 
        this.setLocationRelativeTo(null); 
        this.setVisible(true);
    }
       public void actualizarContador() {
    int totalUsuarios = 0;
    
    // Obtenemos el arreglo real de la Tabla Hash
    EDD.Lista[] arregloListas = tablaUsuarios.getTable();
    
    // Recorremos las 100 posiciones de tu tabla
    for (int i = 0; i < tablaUsuarios.getSize(); i++) {
        // Si hay una lista en esa posición, sumamos cuántos usuarios tiene dentro
        if (arregloListas[i] != null) {
            totalUsuarios += arregloListas[i].getSize();
        }
    }
    

    lblEstado.setText("Usuarios cargados: " + totalUsuarios);
}
       public void avanzarTiempo() {
        // 1. Hacemos "tic" en el reloj usando tu clase RelojSistema
        reloj.tic();

        // 2. Sincronizamos la variable estática por si acaso la usas en otra parte
        tiempoSistema = reloj.getTiempo();

        // 3. Actualizamos el texto en la interfaz (Revisa si tu JLabel se llama jLabel1 o lblTiempo)
        // Cambia 'jLabel1' por el nombre real de tu etiqueta de tiempo en la interfaz
        jLabel1.setText("Tiempo del Sistema: " + tiempoSistema);
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblReloj = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnCargarArchivo = new javax.swing.JButton();
        btnGestionUsuarios = new javax.swing.JButton();
        btnVerCola = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLayeredPane2.setBackground(new java.awt.Color(213, 255, 255));
        jLayeredPane2.setForeground(new java.awt.Color(226, 244, 244));
        jLayeredPane2.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(217, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(220, 255, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(223, 242, 242));

        lblReloj.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblReloj.setText("Tiempo del Sistema: 0");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Gestión Inteligente de Impresión: Prioridad y Eficiencia");

        lblEstado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEstado.setText("Estado: Esperando el archivo...");

        btnCargarArchivo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnCargarArchivo.setText("Cargar Archivo(.txt)");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });

        btnGestionUsuarios.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnGestionUsuarios.setText("Gestion de Usuarios");
        btnGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuariosActionPerformed(evt);
            }
        });

        btnVerCola.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnVerCola.setText("Ver Cola de Impresion");
        btnVerCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerColaActionPerformed(evt);
            }
        });

        btnConfiguracion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnConfiguracion.setText("Configurar Reloj/Sistema");
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        jLabel2.setText("IMPRIMIENDO");

        jLabel3.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel3.setText("tus");

        jLabel4.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        jLabel4.setText("SUEÑOS");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel5.setText("Una pagina a la vez!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblReloj))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 96, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)))))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargarArchivo)
                    .addComponent(btnVerCola, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestionUsuarios)
                    .addComponent(btnConfiguracion))
                .addGap(52, 52, 52))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnSalir)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReloj)
                    .addComponent(lblEstado))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarArchivo)
                    .addComponent(btnGestionUsuarios))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerCola)
                    .addComponent(btnConfiguracion))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
// Abrimos la ventana para buscar el archivo
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    int seleccion = fileChooser.showOpenDialog(this);
    
 
    if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
        
      
        java.io.File archivo = fileChooser.getSelectedFile(); 
        
        // leemos ese archivo que acabamos de guardar en la variable
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
            String linea;
            boolean primeraLinea = true; 
            int contador = 0; 
            
            while ((linea = br.readLine()) != null) {
                if (primeraLinea) {
                    primeraLinea = false;
                    continue; 
                }
                
                String[] partes = linea.split(",");
                
                if (partes.length >= 2) {
                    String nombre = partes[0].trim();
                    String prioridad = partes[1].trim(); 
                    
                    MainClass.Usuario nuevoUser = new MainClass.Usuario(nombre, prioridad);
                    tablaUsuarios.put(nombre, nuevoUser);
                    contador++;
                }
            }
            
            // Actualizamos el Label
            lblEstado.setText("Estado: Cargado (" + contador + " usuarios)");
            javax.swing.JOptionPane.showMessageDialog(this, "Archivo cargado con éxito.");
            
        } catch (Exception e) {
            lblEstado.setText("Estado: Error al cargar");
            javax.swing.JOptionPane.showMessageDialog(this, "Error al leer: " + e.getMessage());
        }
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
    "¿Está seguro que desea cerrar la aplicación?", "Salir", 
    javax.swing.JOptionPane.YES_NO_OPTION);

if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
    System.exit(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuariosActionPerformed
Usuarios vUsuarios = new Usuarios(this); 
    vUsuarios.setVisible(true); // Mostramos usuarios
    this.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionUsuariosActionPerformed

    private void btnVerColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerColaActionPerformed
VerCola ventanaCola = new VerCola(this);

ventanaCola.setVisible(true);
this.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_btnVerColaActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
String entrada = javax.swing.JOptionPane.showInputDialog(this, 
    "Ingrese el tiempo actual del sistema:", 
    "Configurar Reloj", 
    javax.swing.JOptionPane.QUESTION_MESSAGE);

if (entrada != null && !entrada.isEmpty()) {
    try {
        int nuevoTiempo = Integer.parseInt(entrada);
        
        // 1. Actualizamos la variable estática en Inicio
        Interfaces.Inicio.tiempoSistema = nuevoTiempo;
        
        // 2. Actualizamos el JLabel de tu interfaz
        lblReloj.setText("Tiempo del Sistema: " + nuevoTiempo);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Reloj sincronizado a: " + nuevoTiempo);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Debe ingresar un número entero.");
    } 
}// TODO add your handling code here:
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnGestionUsuarios;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerCola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblReloj;
    // End of variables declaration//GEN-END:variables
}
