/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Adriana
 */
public class Inicio extends javax.swing.JFrame {
    public static EDD.TablaHash tablaUsuarios = new EDD.TablaHash(100); 
    public static EDD.MonticuloMinimo colaImpresion = new EDD.MonticuloMinimo(100);
    public static MainClass.RelojSistema reloj = new MainClass.RelojSistema();
    public static EDD.TablaHash duenosDocumentos = new EDD.TablaHash(100);
    public static int tiempoSistema = 0;
    


    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null); // Centrar ventana
        this.setTitle("Sistema de Gestión de Impresión");
        this.setSize(500, 400); 
        this.setLocationRelativeTo(null); 
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        btnCargarArchivo = new javax.swing.JButton();
        btnGestionUsuarios = new javax.swing.JButton();
        btnVerCola = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLayeredPane2.setBackground(new java.awt.Color(213, 255, 255));
        jLayeredPane2.setForeground(new java.awt.Color(226, 244, 244));
        jLayeredPane2.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(217, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(220, 255, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Sistema de Gestion de Impresion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 17, -1, -1));

        btnCargarArchivo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnCargarArchivo.setText("Cargar Archivo(.txt)");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 117, -1, -1));

        btnGestionUsuarios.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnGestionUsuarios.setText("Gestion de Usuarios");
        btnGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 182, -1, -1));

        btnVerCola.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnVerCola.setText("Ver Cola de Impresion");
        btnVerCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerColaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 117, 162, -1));

        btnConfiguracion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnConfiguracion.setText("Configurar Reloj/Sistema");
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 182, -1, -1));

        lblEstado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEstado.setText("Estado: Esperando el archivo...");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 52, -1, -1));

        lblReloj.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblReloj.setText("Tiempo del Sistema: 0");
        getContentPane().add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 52, -1, -1));

        btnSalir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
// 1. Abrimos la ventana para buscar el archivo
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    int seleccion = fileChooser.showOpenDialog(this);
    
 
    if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
        
      
        java.io.File archivo = fileChooser.getSelectedFile(); 
        
        // 3. Ahora sí, leemos ese archivo que acabamos de guardar en la variable
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivo))) {
            String linea;
            boolean primeraLinea = true; 
            int contador = 0; 
            
            while ((linea = br.readLine()) != null) {
                if (primeraLinea) {
                    primeraLinea = false;
                    continue; 
                }
                
                String[] partes = linea.split(",");
                
                if (partes.length >= 2) {
                    String nombre = partes[0].trim();
                    String prioridad = partes[1].trim(); 
                    
                    MainClass.Usuario nuevoUser = new MainClass.Usuario(nombre, prioridad);
                    tablaUsuarios.put(nombre, nuevoUser);
                    contador++;
                }
            }
            
            // Actualizamos el Label
            lblEstado.setText("Estado: Cargado (" + contador + " usuarios)");
            javax.swing.JOptionPane.showMessageDialog(this, "Archivo cargado con éxito.");
            
        } catch (Exception e) {
            lblEstado.setText("Estado: Error al cargar");
            javax.swing.JOptionPane.showMessageDialog(this, "Error al leer: " + e.getMessage());
        }
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
    "¿Está seguro que desea cerrar la aplicación?", "Salir", 
    javax.swing.JOptionPane.YES_NO_OPTION);

if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
    System.exit(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuariosActionPerformed
Usuarios ventanaUsuarios = new Usuarios(); 
    ventanaUsuarios.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionUsuariosActionPerformed

    private void btnVerColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerColaActionPerformed
VerCola ventanaCola = new VerCola();
ventanaCola.setLocationRelativeTo(null); // Para que salga al centro
ventanaCola.setVisible(true);
this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_btnVerColaActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
String entrada = javax.swing.JOptionPane.showInputDialog(this, 
    "Ingrese el tiempo actual del sistema:", 
    "Configurar Reloj", 
    javax.swing.JOptionPane.QUESTION_MESSAGE);

if (entrada != null && !entrada.isEmpty()) {
    try {
        int nuevoTiempo = Integer.parseInt(entrada);
        
        // 1. Actualizamos la variable estática en Inicio
        Interfaces.Inicio.tiempoSistema = nuevoTiempo;
        
        // 2. Actualizamos el JLabel de tu interfaz
        lblReloj.setText("Tiempo del Sistema: " + nuevoTiempo);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Reloj sincronizado a: " + nuevoTiempo);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Debe ingresar un número entero.");
    } 
}// TODO add your handling code here:
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnGestionUsuarios;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerCola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblReloj;
    // End of variables declaration//GEN-END:variables
}
