/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import EDD.Lista; 
import EDD.ElementoMonticulo; 
import EDD.MonticuloMinimo;
import EDD.Nodo;
import EDD.RegistroHash;
import EDD.TablaHash;
import MainClass.Usuario;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Adriana
 */
public class Usuarios extends javax.swing.JFrame {
    private javax.swing.JFrame ventanaPadre;

    javax.swing.table.DefaultTableModel modelo;

    /**
     * Creates new form Usuarios
     */
    public Usuarios(javax.swing.JFrame padre) {
        this.ventanaPadre = padre; 
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana
        this.modelo = (javax.swing.table.DefaultTableModel) tablaUsuarios.getModel();
        cargarTabla();
    }
    
    public void cargarTabla() {
 
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaUsuarios.getModel();
    modelo.setRowCount(0); // Limpiar filas viejas

    // 2. Acceder al arreglo de listas de la Hash (que está en Inicio)
    EDD.Lista[] listas = Interfaces.Inicio.tablaUsuarios.getTable();

    // 3. Recorrer el arreglo
    for (int i = 0; i < Interfaces.Inicio.tablaUsuarios.getSize(); i++) {
        EDD.Lista listaActual = listas[i];
        
        if (!listaActual.isEmpty()) {
            EDD.Nodo aux = listaActual.getpFirst();
            while (aux != null) {
                // Sacamos el RegistroHash y el objeto Usuario
                EDD.RegistroHash reg = (EDD.RegistroHash) aux.getData();
                MainClass.Usuario user = (MainClass.Usuario) reg.getValor();
                
                // Añadimos a la tabla visual
                modelo.addRow(new Object[]{user.getUsername(), user.getTipo()});
                aux = aux.getpNext();
            }
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnVerDocumentos = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 242, 242));

        btnAgregar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar Usuario");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminarUsuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnEliminarUsuario.setText("Eliminar Usuario");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        btnVerDocumentos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnVerDocumentos.setText("Ver Documentos de Usuario");
        btnVerDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDocumentosActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Gestion de Usuarios");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Click ENTER para buscar");

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Prioridad"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);
        if (tablaUsuarios.getColumnModel().getColumnCount() > 0) {
            tablaUsuarios.getColumnModel().getColumn(0).setResizable(false);
            tablaUsuarios.getColumnModel().getColumn(1).setResizable(false);
        }

        txtBuscar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtBuscar.setText("Escribe un nombre para buscar un Usuario...");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnAgregar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVerDocumentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarUsuario)
                        .addGap(75, 75, 75))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDocumentos)
                    .addComponent(btnEliminarUsuario))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
String nombre = txtBuscar.getText().trim();
    
    if (!nombre.isEmpty()) {
        try {
            // Buscamos en la tabla hash que está en la clase Inicio
            // Usamos (MainClass.Usuario) para convertir el Object que devuelve la búsqueda
            Object resultado = Interfaces.Inicio.tablaUsuarios.get(nombre);
            
            if (resultado != null) {
                MainClass.Usuario encontrado = (MainClass.Usuario) resultado;
                
                // Actualizamos la tabla visual
                DefaultTableModel modelo = (DefaultTableModel) tablaUsuarios.getModel();
                modelo.setRowCount(0); // Limpiar tabla
                modelo.addRow(new Object[]{encontrado.getUsername(), encontrado.getTipo()});
            } else {
                JOptionPane.showMessageDialog(this, "El usuario '" + nombre + "' no existe.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: Verifique que la clase Inicio tenga la tablaUsuarios como public static.");
        }
    } else {
        cargarTabla(); // Si está vacío, recarga todos
    }   // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
    int fila = tablaUsuarios.getSelectedRow();
    
    // Verificamos que sí haya seleccionado algo (si es -1, no seleccionó nada)
    if (fila != -1) {
        // 2. Sacamos el nombre del usuario (está en la columna 0)
        String nombreUsuario = tablaUsuarios.getValueAt(fila, 0).toString();
        
        // 3. Eliminamos de la TablaHash GLOBAL que está en Inicio
        boolean eliminado = Interfaces.Inicio.tablaUsuarios.remove(nombreUsuario);
        
        if (eliminado) {
            // 4. Actualizamos la tabla visual de esta misma ventana
            cargarTabla(); 
            
            // 5. ¡LA MAGIA DEL CONTADOR! Le avisamos a la ventana Inicio que actualice su número
            if (this.ventanaPadre != null && this.ventanaPadre instanceof Inicio) {
                ((Inicio)this.ventanaPadre).actualizarContador();
            }
            
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario '" + nombreUsuario + "' eliminado correctamente.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No se pudo eliminar el usuario.");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un usuario de la tabla primero.");
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnVerDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDocumentosActionPerformed
String nombre = "";
    
    // 1. Primero vemos si el usuario hizo clic en alguna fila de la tabla visual
    int filaSeleccionada = tablaUsuarios.getSelectedRow();
    
    if (filaSeleccionada != -1) {
        // Sacamos el nombre de la columna 0 de la fila seleccionada
        nombre = tablaUsuarios.getValueAt(filaSeleccionada, 0).toString();
    } else {
        // 2. Si no seleccionó nada en la tabla, revisamos si escribió algo en la barra
        nombre = txtBuscar.getText().trim();
    }
    
    // 3. Si ambos están vacíos, le pedimos que elija a alguien
    if (nombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario en la tabla o escriba su nombre.");
        return;
    }
    
    // 4. Verificamos que el usuario realmente exista en la TablaHash
    Object resultado = Interfaces.Inicio.tablaUsuarios.get(nombre);
    
    if (resultado != null) {
        
  
        DocumentosUsuario ventanaDocs = new DocumentosUsuario(this);
        
        // Le pasamos el nombre usando el método que creamos
        ventanaDocs.setUsuarioActual(nombre);
        
        // Mostramos la nueva ventana
        ventanaDocs.setVisible(true);
        
        // Cerramos la ventana actual de Usuarios
        this.dispose(); 
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "El usuario '" + nombre + "' no existe en el sistema.");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerDocumentosActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
try {
            // 1. Pedir el nombre del nuevo usuario
            String nombreNuevo = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el nombre del nuevo usuario:");
            if (nombreNuevo == null || nombreNuevo.trim().isEmpty()) {
                return; // Si cancela o deja vacío, no hacemos nada
            }
            
            // Limpiamos los espacios en blanco extra por si acaso
            nombreNuevo = nombreNuevo.trim();

            //  Verificar que el usuario NO exista ya en la TablaHash
            if (Interfaces.Inicio.tablaUsuarios.get(nombreNuevo) != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El usuario '" + nombreNuevo + "' ya existe en el sistema.", "Usuario duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Pedir el tipo de prioridad usando un menú desplegable 
            String[] opciones = {"alta", "media", "baja"};
            String tipoNuevo = (String) javax.swing.JOptionPane.showInputDialog(
                    this, 
                    "Seleccione el tipo de prioridad del usuario:", 
                    "Tipo de Usuario", 
                    javax.swing.JOptionPane.QUESTION_MESSAGE, 
                    null, 
                    opciones, 
                    opciones[2] 
            );

            if (tipoNuevo == null) {
                return; // Si el usuario presiona "Cancelar" en esta ventanita, salimos
            }

            // 4. Crear el nuevo objeto Usuario con el constructor de tu clase
            MainClass.Usuario nuevoUser = new MainClass.Usuario(nombreNuevo, tipoNuevo);

            // 5. Guardarlo en la TablaHash global
        
            Interfaces.Inicio.tablaUsuarios.put(nombreNuevo, nuevoUser); 

            // 6. Actualizar la tabla visual para que el nuevo usuario aparezca instantáneamente
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaUsuarios.getModel();
            
            // Añadimos la fila
            modelo.addRow(new Object[]{nombreNuevo, tipoNuevo});

            // 7. Mensaje de éxito
            javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario '" + nombreNuevo + "' agregado con éxito!");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
if (ventanaPadre != null){
    this.ventanaPadre.setVisible(true);
}
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnVerDocumentos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
