/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.table.DefaultTableModel;
import EDD.MonticuloMinimo;
import EDD.ElementoMonticulo;

/**
 *
 * @author Adriana Julian
 */
public class VerCola extends javax.swing.JFrame {
    private javax.swing.JFrame ventanaPadre;
    public void mostrarSecuencia() {
DefaultTableModel modelo = (DefaultTableModel) tablaCola.getModel();
        modelo.setRowCount(0); 

        EDD.MonticuloMinimo monticulo = Interfaces.Inicio.colaImpresion;
        int tamanoActual = monticulo.getSize();
        EDD.ElementoMonticulo[] arreglo = monticulo.getHeap();

        for (int i = 0; i < tamanoActual; i++) {
            MainClass.RegistroImpresion reg = (MainClass.RegistroImpresion) arreglo[i].getData();
            int etiqueta = reg.getEtiquetaTiempo();

            // Buscamos en la Hash 
            Object busqueda = Interfaces.Inicio.duenosDocumentos.get(String.valueOf(etiqueta));
            
           
            if (busqueda == null) {
                busqueda = Interfaces.Inicio.duenosDocumentos.get(String.valueOf(etiqueta));
            }

            String nombrePersona = ""; // Empezamos vacío

            if (busqueda != null) {
         
                MainClass.RegistroUsuarioCola datos = (MainClass.RegistroUsuarioCola) busqueda;
                nombrePersona = datos.getUsername(); 
            }

            //  Llenar la tabla
            modelo.addRow(new Object[]{
                etiqueta,
                reg.getNombreDocumento(),
                nombrePersona, 
                reg.getTamanoDocumento() + " KB",
                reg.getTipoDocumento()
            });
        }
}


   

    /**
     * Creates new form ColaSecuencia
     */
    public VerCola(javax.swing.JFrame padre) {
        this.ventanaPadre = padre; 
        this.setLocationRelativeTo(null);
        initComponents();
        mostrarSecuencia();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEliminarSeleccionado = new javax.swing.JButton();
        btnGrafico = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCola = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(227, 249, 249));

        jPanel1.setBackground(new java.awt.Color(220, 242, 242));

        btnEliminarSeleccionado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnEliminarSeleccionado.setText("Eliminar Documento Seleccionado");
        btnEliminarSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSeleccionadoActionPerformed(evt);
            }
        });

        btnGrafico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnGrafico.setText("Ver Grafico de Prioridad");
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnSiguiente.setText("Atender al Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Ver Cola");

        tablaCola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prioridad", "Nombre Doc", "Usuario", "Tamano (KB)", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCola);

        btnVolver.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSiguiente)
                                        .addGap(109, 109, 109)
                                        .addComponent(btnEliminarSeleccionado))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(btnGrafico)))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarSeleccionado)
                    .addComponent(btnSiguiente))
                .addGap(18, 18, 18)
                .addComponent(btnGrafico)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
try {
    if (Interfaces.Inicio.colaImpresion.getSize() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay documentos en la cola.");
        return;
    }

    // 1. ELIMINAR MIN devuelve un ElementoMonticulo (el nodo del árbol)
    EDD.ElementoMonticulo nodoEliminado = Interfaces.Inicio.colaImpresion.eliminarMin();

    // 2. EXTRAEMOS el RegistroImpresion que está adentro del nodo
    MainClass.RegistroImpresion atendido = (MainClass.RegistroImpresion) nodoEliminado.getData();

  
    String claveEtiqueta = String.valueOf(atendido.getEtiquetaTiempo());
    Interfaces.Inicio.duenosDocumentos.remove(claveEtiqueta);

   
    mostrarSecuencia(); 
    
    javax.swing.JOptionPane.showMessageDialog(this, "Se ha impreso: " + atendido.getNombreDocumento());

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
} // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
if (ventanaPadre != null){
    this.ventanaPadre.setVisible(true);
}
this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEliminarSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSeleccionadoActionPerformed
int fila = tablaCola.getSelectedRow();
if (fila == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un documento de la tabla.");
    return;
}

// 1. El índice de la tabla coincide con el del arreglo del montículo
int indiceMonticulo = fila; 

// 2. Borrar del montículo
EDD.ElementoMonticulo nodo = Interfaces.Inicio.colaImpresion.eliminarEnPosicion(indiceMonticulo);
MainClass.RegistroImpresion reg = (MainClass.RegistroImpresion) nodo.getData();

// 3. Borrar de la Tabla Hash de dueños
Interfaces.Inicio.duenosDocumentos.remove(String.valueOf(reg.getEtiquetaTiempo()));

// 4. Refrescar
mostrarSecuencia();
javax.swing.JOptionPane.showMessageDialog(this, "Documento eliminado de la cola.");        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSeleccionadoActionPerformed

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
Interfaces.ColaArbol grafica = new Interfaces.ColaArbol(this);
grafica.setVisible(true);
grafica.setLocationRelativeTo(null); // Centrarla        // TODO add your handling code here:
    }//GEN-LAST:event_btnGraficoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCola(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarSeleccionado;
    private javax.swing.JButton btnGrafico;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCola;
    // End of variables declaration//GEN-END:variables
}
