/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.table.DefaultTableModel;
import EDD.MonticuloMinimo;
import EDD.ElementoMonticulo;

/**
 *
 * @author Adriana Julian
 */
public class VerCola extends javax.swing.JFrame {
    public void mostrarSecuencia() {
    DefaultTableModel modelo = (DefaultTableModel) tablaCola.getModel();
    modelo.setRowCount(0); // Limpiar datos viejos

    EDD.MonticuloMinimo monticulo = Interfaces.Inicio.colaImpresion;
    int tamanoActual = monticulo.getSize();
    
    // Obtenemos el arreglo
    EDD.ElementoMonticulo[] arreglo = monticulo.getHeap();

    // Recorremos el montículo para mostrar la secuencia actual
    for (int i = 0; i < tamanoActual; i++) {
        // 1. Extraer datos del documento desde el Montículo
        MainClass.RegistroImpresion reg = (MainClass.RegistroImpresion) arreglo[i].getData();
        int etiqueta = reg.getEtiquetaTiempo();

        // 2. Buscar quién es el dueño usando la Tabla Hash
        Object busqueda = Interfaces.Inicio.duenosDocumentos.get(String.valueOf(etiqueta));
        String nombreUsuario = "Sin dueño";

        if (busqueda != null) {
            MainClass.RegistroUsuarioCola regUser = (MainClass.RegistroUsuarioCola) busqueda;
            nombreUsuario = regUser.getUsername();
        }

        // 3. Añadir a la tabla
        modelo.addRow(new Object[]{
            etiqueta,
            reg.getNombreDocumento(),
            nombreUsuario,
            reg.getTamanoDocumento() + " KB",
            reg.getTipoDocumento()
        });
    }
}


   

    /**
     * Creates new form ColaSecuencia
     */
    public VerCola() {
        initComponents();
        mostrarSecuencia();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCola = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnEliminarSeleccionado = new javax.swing.JButton();
        btnGrafico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(227, 249, 249));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Ver Cola");

        tablaCola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prioridad", "Nombre Doc", "Usuario", "Tamano (KB)", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCola);

        btnVolver.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnSiguiente.setText("Atender al Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnEliminarSeleccionado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnEliminarSeleccionado.setText("Eliminar Documento Seleccionado");
        btnEliminarSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSeleccionadoActionPerformed(evt);
            }
        });

        btnGrafico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnGrafico.setText("Ver Grafico de Prioridad");
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(btnSiguiente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarSeleccionado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnGrafico)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnEliminarSeleccionado))
                .addGap(18, 18, 18)
                .addComponent(btnGrafico)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
try {
    if (Interfaces.Inicio.colaImpresion.getSize() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay documentos en la cola.");
        return;
    }

    // 1. ELIMINAR MIN devuelve un ElementoMonticulo (el nodo del árbol)
    EDD.ElementoMonticulo nodoEliminado = Interfaces.Inicio.colaImpresion.eliminarMin();

    // 2. EXTRAEMOS el RegistroImpresion que está adentro del nodo
    MainClass.RegistroImpresion atendido = (MainClass.RegistroImpresion) nodoEliminado.getData();

  
    String claveEtiqueta = String.valueOf(atendido.getEtiquetaTiempo());
    Interfaces.Inicio.duenosDocumentos.remove(claveEtiqueta);

   
    mostrarSecuencia(); 
    
    javax.swing.JOptionPane.showMessageDialog(this, "Se ha impreso: " + atendido.getNombreDocumento());

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
} // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
Interfaces.Inicio menu = new Interfaces.Inicio();
menu.setVisible(true);


this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEliminarSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSeleccionadoActionPerformed
int fila = tablaCola.getSelectedRow();
if (fila == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un documento de la tabla.");
    return;
}

// 1. El índice de la tabla coincide con el del arreglo del montículo
int indiceMonticulo = fila; 

// 2. Borrar del montículo
EDD.ElementoMonticulo nodo = Interfaces.Inicio.colaImpresion.eliminarEnPosicion(indiceMonticulo);
MainClass.RegistroImpresion reg = (MainClass.RegistroImpresion) nodo.getData();

// 3. Borrar de la Tabla Hash de dueños
Interfaces.Inicio.duenosDocumentos.remove(String.valueOf(reg.getEtiquetaTiempo()));

// 4. Refrescar
mostrarSecuencia();
javax.swing.JOptionPane.showMessageDialog(this, "Documento eliminado de la cola.");        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarSeleccionadoActionPerformed

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
Interfaces.ColaArbol grafica = new Interfaces.ColaArbol();
grafica.setVisible(true);
grafica.setLocationRelativeTo(null); // Centrarla        // TODO add your handling code here:
    }//GEN-LAST:event_btnGraficoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarSeleccionado;
    private javax.swing.JButton btnGrafico;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCola;
    // End of variables declaration//GEN-END:variables
}
